version: 2.1

orbs:
  terraform: circleci/terraform@3.0.0

jobs:
  plan:
    parameters:
      root-module-path:
        type: string
        default: '.'
    executor: terraform/default
    working_directory: ~/src
    steps:
      - checkout
      - run:
          command: >-
            echo "credentials \"app.terraform.io\" {token =
            \"$TERRAFORM_TOKEN\"}" > $HOME/.terraformrc
          name: Create .terraformrc file locally
      - terraform/validate:
          path: .
      - terraform/init:
          backend: true
          path: << parameters.root-module-path >>
      - terraform/plan:
          path: << parameters.root-module-path >>
          var_file: 'variables.tfvars'
  apply:
    parameters:
      root-module-path:
        type: string
        default: '.'
    executor: terraform/default
    working_directory: ~/src
    steps:
      - checkout
      - run:
          command: >-
            echo "credentials \"app.terraform.io\" {token =
            \"$TERRAFORM_TOKEN\"}" > $HOME/.terraformrc
          name: Create .terraformrc file locally
      - terraform/init:
          backend: true
          path: << parameters.root-module-path >>
      - terraform/apply:
          path: << parameters.root-module-path >>
          var_file: 'variables.tfvars'

workflows:
  version: 2
  deploy_infrastructure_api_heroku_dev_us:
    jobs:
      - plan:
          filters:
            branches:
              only:
                - main
      - request-apply:
          type: approval
          requires:
            - plan
      - apply:
          requires:
            - request-apply
